// This file is auto-generated by the Supabase CLI to generate the database types
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          name: string | null
          password: string | null
          role: string
          emailVerified: Date | null
          image: string | null
          lastLoginAt: Date | null
          lastActiveAt: Date | null
          hasBoughtTicket: boolean
          lastEventAttendedId: string | null
          attendedLastEvent: boolean
          hasRequestedRefund: boolean
          refundRequestedAt: Date | null
          hasBeenRefunded: boolean
          refundedAt: Date | null
          createdAt: Date
          updatedAt: Date
          authExternalId: string | null
          stripeCustomerId: string | null
        }
        Insert: {
          id?: string
          email: string
          name?: string | null
          password?: string | null
          role?: string
          emailVerified?: Date | null
          image?: string | null
          lastLoginAt?: Date | null
          lastActiveAt?: Date | null
          hasBoughtTicket?: boolean
          lastEventAttendedId?: string | null
          attendedLastEvent?: boolean
          hasRequestedRefund?: boolean
          refundRequestedAt?: Date | null
          hasBeenRefunded?: boolean
          refundedAt?: Date | null
          createdAt?: Date
          updatedAt?: Date
          authExternalId?: string | null
          stripeCustomerId?: string | null
        }
        Update: {
          id?: string
          email?: string
          name?: string | null
          password?: string | null
          role?: string
          emailVerified?: Date | null
          image?: string | null
          lastLoginAt?: Date | null
          lastActiveAt?: Date | null
          hasBoughtTicket?: boolean
          lastEventAttendedId?: string | null
          attendedLastEvent?: boolean
          hasRequestedRefund?: boolean
          refundRequestedAt?: Date | null
          hasBeenRefunded?: boolean
          refundedAt?: Date | null
          createdAt?: Date
          updatedAt?: Date
          authExternalId?: string | null
          stripeCustomerId?: string | null
        }
      }
      events: {
        Row: {
          id: string
          title: string
          slug: string
          description: string
          content: string | null
          image: string | null
          gallery: string[] | null
          brand: string
          category: string
          tags: string[] | null
          date: Date
          time: string
          location: string
          address: string | null
          city: string
          country: string
          capacity: number
          sold: number
          featured: boolean
          status: 'DRAFT' | 'PUBLISHED' | 'CANCELLED'
          meta_title: string | null
          meta_description: string | null
          meta_keywords: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          slug: string
          description: string
          content?: string | null
          image?: string | null
          gallery?: string[] | null
          brand: string
          category: string
          tags?: string[] | null
          date: string | Date
          time: string
          location: string
          address?: string | null
          city: string
          country: string
          capacity: number
          sold?: number
          featured?: boolean
          status?: 'DRAFT' | 'PUBLISHED' | 'CANCELLED'
          meta_title?: string | null
          meta_description?: string | null
          meta_keywords?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          slug?: string
          description?: string
          content?: string | null
          image?: string | null
          gallery?: string[] | null
          brand?: string
          category?: string
          tags?: string[] | null
          date?: string | Date
          time?: string
          location?: string
          address?: string | null
          city?: string
          country?: string
          capacity?: number
          sold?: number
          featured?: boolean
          status?: 'DRAFT' | 'PUBLISHED' | 'CANCELLED'
          meta_title?: string | null
          meta_description?: string | null
          meta_keywords?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      ticket_tiers: {
        Row: {
          id: string
          event_id: string
          name: string
          description: string | null
          price: number
          currency: string
          quantity: number
          sold: number
          available: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          event_id: string
          name: string
          description?: string | null
          price: number
          currency?: string
          quantity: number
          sold?: number
          available?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          event_id?: string
          name?: string
          description?: string | null
          price?: number
          currency?: string
          quantity?: number
          sold?: number
          available?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      orders: {
        Row: {
          id: string
          order_number: string
          event_id: string
          user_id: string | null
          customer_name: string
          customer_email: string
          customer_phone: string | null
          total_amount: number
          currency: string
          status: string
          payment_intent_id: string | null
          payment_status: string
          payment_method: string | null
          payment_date: string | null
          refunded: boolean
          refunded_at: string | null
          refund_amount: number | null
          refund_reason: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          order_number: string
          event_id: string
          user_id?: string | null
          customer_name: string
          customer_email: string
          customer_phone?: string | null
          total_amount: number
          currency: string
          status?: string
          payment_intent_id?: string | null
          payment_status?: string
          payment_method?: string | null
          payment_date?: string | null
          refunded?: boolean
          refunded_at?: string | null
          refund_amount?: number | null
          refund_reason?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          order_number?: string
          event_id?: string
          user_id?: string | null
          customer_name?: string
          customer_email?: string
          customer_phone?: string | null
          total_amount?: number
          currency?: string
          status?: string
          payment_intent_id?: string | null
          payment_status?: string
          payment_method?: string | null
          payment_date?: string | null
          refunded?: boolean
          refunded_at?: string | null
          refund_amount?: number | null
          refund_reason?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      order_items: {
        Row: {
          id: string
          order_id: string
          ticket_tier_id: string
          quantity: number
          unit_price: number
          currency: string
          total_price: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          order_id: string
          ticket_tier_id: string
          quantity: number
          unit_price: number
          currency: string
          total_price: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          order_id?: string
          ticket_tier_id?: string
          quantity?: number
          unit_price?: number
          currency?: string
          total_price?: number
          created_at?: string
          updated_at?: string
        }
      }
      newsletter_subscriptions: {
        Row: {
          id: string
          email: string
          user_id: string | null
          active: boolean
          subscribed_at: string
          unsubscribed_at: string | null
          updated_at: string
        }
        Insert: {
          id?: string
          email: string
          user_id?: string | null
          active?: boolean
          subscribed_at?: string
          unsubscribed_at?: string | null
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          user_id?: string | null
          active?: boolean
          subscribed_at?: string
          unsubscribed_at?: string | null
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
