-- This migration documents the changes made to update webhook handlers to use the orders table
-- instead of the now-removed bookings table.

-- The following changes were made in the application code:
-- 1. In src/app/api/webhooks/stripe/route.ts:
--    - Updated all database operations to use the 'orders' table
--    - Updated column names to match the orders table schema (camelCase)
--    - Updated the handleCheckoutSession function to work with the orders table
--
-- 2. In src/app/api/webhooks/test/route.ts:
--    - Updated test webhook handler to use the 'orders' table
--    - Updated column names to match the orders table schema

-- The following columns were mapped from the old bookings table to the orders table:
-- - payment_status -> paymentStatus
-- - payment_intent_id -> paymentIntentId
-- - stripe_session_id -> stripeSessionId
-- - customer_email -> customerEmail
-- - customer_name -> customerName
-- - amount_paid -> amount (converted from cents to dollars)
-- - created_at -> createdAt
-- - updated_at -> updatedAt
-- - status -> status (kept as is)
-- - ticket_type -> ticketType
